version: 2
jobs:
  build:
    working_directory:working_directory: ~/CI-CDdemo
    docker:
      - image: circleci/node:10-browsers
    steps:
      - checkout
      - restore_cache:
          key: CI-CDdemo-{{ .Branch }}-{{ checksum "./angular-demo/package-lock.json" }}
      - run: cd angular-demo && npm install
      - save_cache:
          key: CI-CDdemo-{{ .Branch }}-{{ checksum "./angular-demo/package-lock.json" }}
          paths:
            - "node_modules"
      - run: cd angular-demo && npm run test -- --no-watch --no-progress --browsers=ChromeHeadlessCI
      - run: cd angular-demo && npm run e2e -- --protractor-config=e2e/protractor-ci.conf.js

workflows:
    version: 2
    # the test workflow
    build_and_test:
        jobs:
          - build:
              filters:
                  branches:
                      only:
                          - develop
                          - staging
                          - master
                          - main