version: 2
jobs:
  build:
    working_directory: ~/CI-CDdemo
    docker:
      - image: circleci/node:6-browsers
    steps:
      - checkout
      - run: cd angular-demo && ls

      - restore_cache:
          key: dependency-cache-{{ checksum "./angular-demo/yarn.lock" }}
      - run:
          name: install-dependencies
          command: cd angular-demo && yarn install
      - save_cache:
          key: dependency-cache-{{ checksum "./angular-demo/yarn.lock" }}
          paths:
            - ./angular-demo/.cache/yarn
            - ./angular-demo/node_modules
      - run:
          name: angular-build
          command:  cd angular-demo && yarn ng -- build --prod --aot --no-progress
      - run:
          name: angular-test
          command:  cd angular-demo && yarn test -- --single-run --no-progress
      - store_artifacts:
          path:  ./angular-demo/test-results.xml
      - run:
          name: angular-lint
          command:  cd angular-demo && yarn lint -- --formatters-dir ./tslint-formatters --format junit -o tslint.xml
      - store_artifacts:
          path: ./angular-demo/tslint.xml
